repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      # - id: detect-aws-credentials
      - id: detect-private-key
  # - repo: meta
    # hooks:
      # - id: check-useless-excludes # Ensure the exclude syntax is correct
      # - id: check-hooks-apply # Fails if a hook doesn't apply to any file
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    - id: black-jupyter
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.258'
    hooks:
      - id: ruff
default_language_version:
  python: python3.10
# Don't check dirs/files that are brought in from other repositories
# exclude: resources/samplers/|resources/options_lookup.tsv
